w05d03/rails-nested-forms/starter/music_manager/config/routes.rb
Rails.application.routes.draw do

  resources :albums do
  	resources :songs
	end
  root "albums#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

w05d03/rails-nested-forms/starter/music_manager/app/models/album.rb
class Album < ApplicationRecord
	has_many :albums_song
	has_many :songs, through: :albums_song
end

w05d03/rails-nested-forms/starter/music_manager/app/models/albums_song.rb
class AlbumsSong < ApplicationRecord
	belongs_to :album
	belongs_to :song
end

w05d03/rails-nested-forms/starter/music_manager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w05d03/rails-nested-forms/starter/music_manager/app/models/song.rb
class Song < ApplicationRecord
	has_many :albums_song
	has_many :albums, through: :albums_song
end

w05d03/rails-nested-forms/starter/music_manager/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create

    new_album = Album.create(album_params)
    new_album.save

    redirect_to new_album

  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    album = Album.find(params[:id])
    album.update(album_params)

    redirect_to album
  end

  def destroy
    Album.destroy(params[:id])
    redirect_to albums_url
  end

  protected
  def album_params
    params.require(:album).permit(:name, :genre)
  end
end

w05d03/rails-nested-forms/starter/music_manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

w05d03/rails-nested-forms/starter/music_manager/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @album = Album.find(params[:album_id])
    @songs = @album.songs
  end

  def show
    @album = Album.find(params[:album_id])
    @song = @album.songs.find(params[:id])
  end

  def new
    @album = Album.find(params[:album_id])
    @song = Song.new  
  end

  def create
    album = Album.find(params[:album_id])
    song = album.songs.create(song_params)

    show_page = album_song_path(album.id, song.id)
    redirect_to show_page
  end

  def edit
    @album = Album.find(params[:album_id])
    @song = @album.songs.find(params[:id])
  end

  def update
    album = Album.find(params[:album_id])
    song = album.songs.find(params[:id])
    song.update(song_params)

    show_page = album_song_path(album.id, params[:id])
    redirect_to show_page
  end

  def destroy
    Album.find(params[:album_id]).songs.destroy(params[:id])
    redirect_to album_url
  end

  protected
  def song_params
    params.require(:song).permit(:title, :duration)
  end
end

w05d03/rails-nested-forms/starter/music_manager/app/helpers/albums_helper.rb
module AlbumsHelper
end

w05d03/rails-nested-forms/starter/music_manager/app/helpers/application_helper.rb
module ApplicationHelper
end

w05d03/rails-nested-forms/starter/music_manager/app/views/albums/_album.html.erb
<p>Title: <%= album.name %></p>
<p>Genre: <%= album.genre %></p>

<%= link_to "Show Page", album if action_name == "index" %> |
<%= link_to "Edit Page", edit_album_path(album) %>

<br>
--------------------------------------

w05d03/rails-nested-forms/starter/music_manager/app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :genre %>
  <%= f.text_field :genre %>

  <%= f.submit %>


<% end %>

w05d03/rails-nested-forms/starter/music_manager/app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form" %>

w05d03/rails-nested-forms/starter/music_manager/app/views/albums/index.html.erb
<h1>All Albums</h1>

<%= link_to "New Album", new_album_path %>

<%= render @albums %>

w05d03/rails-nested-forms/starter/music_manager/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

w05d03/rails-nested-forms/starter/music_manager/app/views/albums/show.html.erb
<h1>Album Show Page</h1>

  <%= render @album %>

<br>

<%= link_to "Edit", edit_album_path(@album) %> |
<%= link_to "Back", albums_path %> |

<%= link_to "Destroy", @album, method: :delete, data: { confirm: "Are you sure?" } %>

w05d03/rails-nested-forms/starter/music_manager/app/views/songs/_form.html.erb
<%= form_for([@album,@song]) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :duration %>
  <%= f.number_field :duration, step: :any %>

  <%= f.submit %>


<% end %>

w05d03/rails-nested-forms/starter/music_manager/app/views/songs/_song.html.erb
<p>Title: <%= song.title %> - <em><%= song.duration %></em>

  <%= link_to "Show Page", album_song_path(@album, song) if controller_name == "songs" %> - 
  <%= link_to "Edit Page", edit_album_song_path(@album, song) if controller_name == "songs" %>
</p>

w05d03/rails-nested-forms/starter/music_manager/app/views/songs/edit.html.erb
<h1>Edit Songs</h1>

<%= render "form" %>

w05d03/rails-nested-forms/starter/music_manager/app/views/songs/index.html.erb
<h1>All Songs</h1>

<%= link_to "New Song", new_album_song_path %>

<%= render @songs %>

w05d03/rails-nested-forms/starter/music_manager/app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

w05d03/rails-nested-forms/starter/music_manager/app/views/songs/show.html.erb
<h1>Song Show Page</h1>

  <%= render @song %>

<br>


<%= link_to "Back", album_songs_path %> |

<%= link_to "Destroy", album_song_path, method: :delete, data: { confirm: "Are you sure?" } %>